#!/bin/sh
xrdb ~/.config/x11/Xresources
xrdb -merge ~/.cache/wal/colors.Xresources

eval $(gnome-keyring-daemon --start)
export SSH_AUTH_SOCK

xwallpaper --zoom $(cat ~/.config/wallpaper.conf) &
xautolock -locker slocker -notifier "notify-send Locking laptop in 15s" -notify 15 -time 10 &
xset r rate 250 45 &
sxhkd &
dunst &
flameshot &
xcompmgr &
sbar &

while type dwm >/dev/null ; do dwm && continue || break ; done
