#!/bin/sh
xrdb ~/.config/x11/Xresources
xrdb -merge ~/.cache/wal/colors.Xresources

eval $(/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh)
export GNOME_KEYRING_CONTROL GNOME_KEYRING_PID GPG_AGENT_INFO SSH_AUTH_SOCK


xwallpaper --zoom $(cat ~/.config/wallpaper.conf)
sbar &
#xautolock -locker slocker -notifier "notify-send Locking laptop in 15s" -notify 15 -time 10 &
batsignal -i -M "sudo light -S 10" -c 10 -d 5 -D "systemctl suspend" -b &
xset r rate 250 45 &
sxhkd &
dunst &
flameshot &
nm-applet &
xcompmgr &

while type dwm >/dev/null ; do dwm && continue || break ; done
